### ISSUE TITLE
Not working for Europe

### ISSUE THREAD

**Issue by daneeq** [Nimrod007/waze-api#1]
Hi, I wanted to try this but after some experimentation, it only worked for the US. I tried the UK, Czech Republic and Israel, and I always got an error from the API. It looks to me as if the API request can't locate the start or end points with coordinates in Europe. Are you getting the same, and could it be that their API is designed this way for some reason?

Thanks,
Dan

**Comment by Nimrod007** [comment]
for israel checkout:
https://github.com/Nimrod007/waze-api/tree/master/israelServer

for others ill check and upte

**Comment by Nimrod007** [comment]
Hi, this example only includes USA server,
for Europe support please use the api:
<a href="https://www.mashape.com/bestapi/waze-calculate-route-duration?&amp;utm_campaign=mashape5-embed&amp;utm_medium=button&amp;utm_source=waze-calculate-route-duration&amp;utm_content=anchorlink&amp;utm_term=icon-dark"> mashape <img src="https://d1g84eaw0qjo7s.cloudfront.net/images/badges/badge-icon-dark-6460f8cc.png" width="143" height="38" alt="Mashape"></a>
