### ISSUE TITLE
Why on get address list you use that fixed lat/long?

### ISSUE THREAD

**Issue by prsolucoes** [Nimrod007/waze-api#11]
Why on get address list you use that fixed lat/long?

It covers all the world or is only to bring address near you?

Thanks.

**Comment by Nimrod007** [comment]
sorry for the last response...
not sure i understand the question.. why not use what ?

**Comment by prsolucoes** [comment]
When you get the address list you send a fixed parameter to waze API. I dont understand why you use it.

**Comment by Nimrod007** [comment]
when asking a question its nice to add code your talking about ...
so if your talking about this:
https://github.com/Nimrod007/waze-api/blob/f7cc77cddeb704e91ec2890d6b8631df3ff5673c/src/main/java/com/waze/service/WazeRouteService.java#L240

they require some lang and lot so i added something
