### ISSUE TITLE
Traffic Notification blank

### ISSUE THREAD

**Issue by hellracer** [Nimrod007/waze-api#13]
HI,
I tried to get a traffic notification out of this bounding box coordinates it seems like it's not working 

LATTOP=14.40192039417
LONLEFT=121.00014167566
LATBOT=14.45587960583
LONRIGHT=121.05585832434

app1: localhost:8080  - Traffic Notifications
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /waze/traffic-notifications?latBottom=14.45587960583&latTop=14.40192039417&lonLeft=121.00014167566&lonRight=121.05585832434 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: application/json
>
< HTTP/1.1 200 OK
< Date: Wed, 08 Mar 2017 02:55:40 GMT
< Content-Type: application/json
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
<
{ [9538 bytes data]

**Comment by hellracer** [comment]
I even intertwine the values just to make sure but still no results? did waze stop this anymore?

**Comment by hellracer** [comment]
Is it possible to choose a server from conf.yaml? i believed the problem lies on where I am from asia :)

**Comment by Nimrod007** [comment]
ill app this option soon and update once its done

**Comment by hellracer** [comment]
Thanks, still struggling how to make this work last year it was working fine me anyway :)

**Comment by priyanka06** [comment]
@nimrod007
Can u help me how i can get the speed data from waze API?

**Comment by Fa5g** [comment]
Very interesting the notifications info generated by this api. If were included the pictures sent by the user, would be better. Regards.

**Comment by Fa5g** [comment]
Hi @Nimrod007, how many request per day can I apply for this api? Thanks.

**Comment by Nimrod007** [comment]
i dont know, it goes to waze backend server which has some limit, you can just test this and see when you start to get blocked
