### ISSUE TITLE
Failed to query waze route

### ISSUE THREAD

**Issue by duylong** [Nimrod007/waze-api#6]
Hi,

Sometimes, I get this error in my log: 

```
ERROR [2016-04-15 11:44:53,765] waze: failed to routesXYwithDirections: failed to query waze route
url: https://www.waze.com/row-RoutingManager/routingRequest?from=x%3AX.XX+y%3AX.XX&to=x%3AX.XX+y%X.XX&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=3&options=AVOID_TRAILS%3At
error: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html>^M
<head><title>503 Service Temporarily Unavailable</title></head>^M
<body bgcolor="white">^M
<center><h1>503 Service Temporarily Unavailable</h1></center>^M
<hr><center>nginx</center>^M
</body>^M
</html>^M
; line: 1, column: 2]
```

My browser output: 

```
failed to get routes with directions by x,y
```

My curl output:

```
HTTP/1.1 500 Internal Server Error
Date: Fri, 15 Apr 2016 12:18:36 GMT
* Server Apache is not blacklisted
Server: Apache
Content-Type: text/plain
Content-Length: 43
Connection: close
```

No problem, when I request Waze directly with the URL in the log: 

```
HTTP/1.1 200 OK
* Server nginx is not blacklisted
Server: nginx
Date: Fri, 15 Apr 2016 12:20:36 GMT
Content-Type: text/x-json
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000; includeSubDomains;
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=0;  preload
X-Content-Type-Options: nosniff
Via: 1.1 google
```

Do you know this issue ?

**Comment by Nimrod007** [comment]
```
<head><title>503 Service Temporarily Unavailable</title></head>^M
```

waze seems to block you or they are down ...

**Comment by duylong** [comment]
It success when I run directly the curl command: 
```
https://www.waze.com/row-RoutingManager/routingRequest?from=x%3AX.XX+y%3AX.XX&to=x%3AX.XX+y%X.XX&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=3&options=AVOID_TRAILS%3At
```
It's strange, I get sometimes a result to this API, no errors. Do you know the default http headers ?

Other problem, I get a 404 with https://www.waze.com/il-RoutingManager/routingRequest?from=...

**Comment by Liorfru** [comment]
I also have the same issue, Query addresses in Israel fail while USA works!

**Comment by Nimrod007** [comment]
just checked and its wokring:
https://www.waze.com/il-RoutingManager/routingRequest?from=x%3A34.7652473449707+y%3A32.07120132446289&to=x%3A34.887760162353516+y%3A32.084041595458984&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=3&options=AVOID_TRAILS%3At

please provide full url that isnt working for you

**Comment by Liorfru** [comment]
Query this route  with row-RoutingManager fail and with il-RoutingManager pass

is there a way to force the query to il-RoutingManager 

ERROR [2016-04-18 21:09:11,818] waze: failed to getRoutes: failed to query waze
route
url: https://www.waze.com/row-RoutingManager/routingRequest?from=x%3A34.82747650
1464844+y%3A32.081329345703125&to=x%3A34.76401138305664+y%3A32.06797790527344&at
=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&n
Paths=3&options=AVOID_TRAILS%3At
error: Unexpected character ('<' (code 60)): expected a valid value (number, Str
ing, array, object, 'true', 'false' or 'null')
 at [Source: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
; line: 1, column: 2]
192.168.10.1 - - [18/Apr/2016:21:09:08 +0000] "GET /waze/routes?end=Ha-Yarkon%20
St%203,%20Tel%20Aviv-Yafo&start=HaRav%20Ahronson%20St%2012,%20Bnei%20Brak HTTP/1
.1" 500 20 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/49.0.2623.112 Safari/537.36" 2970

**Comment by Nimrod007** [comment]
are you using this as a server ? or just embedded the waze service in your existing code ?

**Comment by Liorfru** [comment]
Server

**Comment by Nimrod007** [comment]
I can add an option to add configuration for which RoutingManager you want to use (so you can only use the il 1...) this will probably take some time 
ill update when ready and add docs for this

**Comment by Liorfru** [comment]
That would be great,
Thanks.

**Comment by duylong** [comment]
Finally I use Waze coordinates instead of Google Maps coordinates, the problem 404 perhaps comes from there.

Good idea for the enhancement. Here is an example with "row-RoutingManager" and the 503 error:

OK with browser from France: 
https://www.waze.com/row-RoutingManager/routingRequest?from=x%3A7.754208599999999+y%3A48.5878653&to=x%3A7.764597499999999+y%3A48.5833868&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=3&clientVersion=4.0.0&options=AVOID_TRAILS%3At%2CALLOW_UTURNS%3At

NOK with the API from France:
https://DOMAIN/waze/routesXYwithDirections?endLat=48.5833868&endLon=7.764597499999999&startLat=48.5878653&startLon=7.754208599999999

**Comment by kissscool** [comment]
Hello Duylong,

I have a question regarding your query. What "cost" stand for in the results xml ?(It looks like "time")
Is time consider traffic ?

I would like to know if we can specify departure time in the query ? maybe by changing "At=0" ?

**Comment by ruudvddries** [comment]
Is anyone still getting a respons from the waze API (row-RoutingManager)? I get a 403 every time I try. For example this request;

https://www.waze.com/row-RoutingManager/routingRequest?from=x%3A5.8372264+y%3A51.8125626&to=x%3A5.879318+y%3A52.561847&at=0&returnJSON=true&timeout=60000&nPaths=1&clientVersion=4.0.0&RoutingType=ROUTE_SHORTEST_DISTANCE

Hope you have a solution to avoid this 403!

Regards,

Ruud

**Comment by kissscool** [comment]
Hi Ruud, I have the same issue. I didn't find any solution at this moment.

**Comment by Nimrod007** [comment]
it might be that waze have a new threshold for this api and when you hit it you get a 403 response.

**Comment by boreut** [comment]
Having the same issue, anyone found a way to get the RountingManager working?

**Comment by abarnes** [comment]
Anybody figure out the 403 issue with routing? I got 403 on my first request, so it's not throttling.  I got 403 with the URL in the readme:

curl -v "http://localhost:8080/waze/routesWithDirections?end=156+5th+Avenue%2C+New+York%2C+NY+10010&start=6+East+57th+Street%2C+New+York%2C+NY+10022" -H "Accept: application/json"

**Comment by ruudvddries** [comment]
I think it is a host header cross site scripting protection implemented at
Waze their servers. Anyone got a clue on how to avoid that?

Regards,

Ruud

**Comment by fPecc** [comment]
Reopening because the RoutingManager still throws the "403 Forbidden" error, using any of the URLs listed above.

**Comment by duczz** [comment]
@Nimrod007 I have the 503 Error too :-(
