### ISSUE TITLE
Merge Lat and Long

### ISSUE THREAD

**Issue by duylong** [Nimrod007/waze-api#7]
Hi,

I use some apps with this format "Lat,Lon". Can you add a feature in order to use this format ? Moreover it simplify the URL query. For example:

https://DOMAIN/waze/routesXYwithDirections?end=48.5833868,7.764597499999999&start=48.5878653,7.754208599999999

Best regards,

**Comment by Nimrod007** [comment]
wont fix, just split the lat lon to 2 params.

if you want to you can add this with a pull request.
thanks
