### ISSUE TITLE
Speed Traps

### ISSUE THREAD

**Issue by sadanro100** [Nimrod007/waze-api#9]
Should we expect to retrieve speed traps with any of the endpoints?

**Comment by Nimrod007** [comment]
did you take a look at Traffic Notifications ? try to send it for a route you know waze returns a speed trap and see if you get it in results

**Comment by sadanro100** [comment]
I had already tried it, but just to double check, here's a response from a wide area of São Paulo, Brazil, where there are lots of speed traps.

curl -v "http://localhost:8080/waze/traffic-notifications?latBottom=-23.677763&latTop=-23.598159&lonLeft=-46.723901&lonRight=-46.647144" -H "Accept: application/json"

http://pastebin.com/5zrMbcnf

There are Police reports, but no speed cameras :(

I was planning to scrape the web version of Waze, but your solution would be much easier to get them...

**Comment by priyanka06** [comment]
@sadanro100
How to get the speed from waze?

**Comment by priyanka06** [comment]
@sadanro100
Can u help me, i need ur help

**Comment by Nimrod007** [comment]
@sadanro100 - Hi, i dont know exactly how to get the speed data.

try to get notifications for the area you want, see the result and check if the speed traps are there. 

if not i cant help you.
good luck
